---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customermanagementapi
  labels:
    env: prod 
    version: "1.0"
spec:
  minReadySeconds: 5
  replicas: 1
  selector: 
    matchLabels: 
      env: prod 
      version: "1.0"
  strategy: 
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 1
  template: 
    metadata:
      name: customermanagementapi
      labels: 
        env: prod 
        version: "1.0"
    spec: 
      restartPolicy: Always
      containers: 
        - name: customermanagementapi
          image: pitstop/customermanagementapi:1.0
          ports: 
            - name: customer1
              containerPort: 5100
          resources: 
            limits: 
              cpu: "100m"
              memory: "200Mi"
          env: 
            - name: ASPNETCORE_ENVIRONMENT
              value: Production



---


apiVersion: v1
kind: Service
metadata:
  name: customermanagementapi
  labels: 
    env: prod 
    version: "1.0"
spec: 
  type: ClusterIP
  clusterIP: None 
  selector:
    env: prod 
    version: "1.0"
  ports: 
    - name: cust-svc 
      port: 5100
      targetPort: 5100