
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logserver
  labels:
    env: prod 
    version: "1.0"
spec:
  minReadySeconds: 5
  replicas: 1
  selector: 
    matchLabels: 
      env: prod 
      version: "1.0"
  strategy: 
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 1
  template: 
    metadata:
      name: logserver
      labels: 
        env: prod 
        version: "1.0"
    spec: 
      restartPolicy: Always
      containers: 
        - name: log1  
          image: datalust/seq:latest
          ports: 
            - name: log1 
              containerPort: 5341
          resources: 
            limits: 
              cpu: "100m"
              memory: "200Mi"
          env: 
            - name: ACCEPT_EULA
              value: "Y"

---

apiVersion: v1
kind: Service
metadata:
  name: logserver
  labels: 
    env: prod
    version: "1.0"
spec: 
  type: NodePort
  selector:
    env: prod 
    version: "1.0"
  ports: 
    - name: logsvc  
      port: 5341
      targetPort: 80
      nodePort: 30006
