---
apiVersion: v1 
kind: Pod
metadata:
  name: apache
spec: 
  restartPolicy: Never
  nodeSelector:
    env: dev
  containers:
    - name: apache
      image: httpd
      ports:
        - name: apache
          containerPort: 80