---
apiVersion: v1
kind: Pod
metadata:
  name: toleration 
spec:
  restartPolicy: Never
  tolerations:
    - key: team 
      operator: Equal
      value: devops
      effect: NoSchedule
  Containers:
    - name: nginx
      image: nginx
      ports:
        - name: nginx
          containerPort: 80


---
---
apiVersion: v1
kind: Pod
metadata:
  name: notoleration 
spec:
  restartPolicy: Never
  Containers:
    - name: nginx
      image: nginx
      ports:
        - name: nginx
          containerPort: 80