apiVersion: v1
kind: PersistentVolume
metadata:
  name: appsoc-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: kube-storage-secret
    shareName: my-share
  storageClassName: appsocstorageclass