apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: appsoc-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: appsocstorageclass
  volumeName: appsoc-pv