---
- name: install tomcat on ubuntu
  hosts: appserver
  become: yes
  tasks: 
    - name: fail for unsupported os 
      ansible.builtin.fail:
        msg: 'this works only on ubuntu os'
      when: ansible_facts['distribution'] != "Ubuntu"
    - name: update and install tomcat
      ansible.builtin.apt:
        name: "{{ package }}"
        update_cache: yes
        state: present 
    - name: create tomcat user
      ansible.builtin.user:
        name: "{{ user }}" 
        create_home: true
        group: "{{ group }}"
        home: "{{ home_dir }}"
        shell: "{{ user_shell }}"
        system: true
        state: present   
    - name: download tomcat tar 
      ansible.builtin.unarchive:
        src: "{{ tomcat_url }}"
        dest: "{{ home_dir }}"
        owner: "{{ user }}"
        remote_src: yes
      become: yes
    - name: check the file exists
      ansible.builtin.stat:
        path: /tmp/apache-tomcat-10.0.10.tar.gz
    - name: debug variables
      ansible.builtin.debug:
        msg: print the necessary variables
    - name: find all the shell files
      find:
        paths: "/opt/tomcat/apache-tomcat-10.0.10/bin"
        patterns: '*.sh'
      register: shell_files
    - name: change permissions to execute
      file:
        path: "{{ item.path }}"
        owner: "{{ user }}"
        group: "{{ group }}"
        mode: "755"
      loop: "{{ shell_files.files }}"