---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ajay
  labels:
    app: nginx
    env: dev
spec:
  minReadySeconds: 3
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        env: dev
    spec:
      containers:
        - name: nginx
          image: nginx
          resources:
            limits:
              cpu: "50m"
              memory: "50Mi"
