---

pool:
  name: Default

trigger:
  - main

steps:
  - task: Docker@2
    displayName: 'Build docker image and push to repository'
    inputs:
      command: buildAndPush
      Dockerfile: 'Dockerfile'
      containerRegistry: 'Dockerhub'
      repository: 'ajaykumar020/springpetclinic'
      tags: "latest"
  - task: Bash@3
    displayName: "Execute terraform"
    inputs:
      targetType: inline
      script: "terraform init && terraform apply -auto-approve"
      workingDirectory: 'deployment/terraform'
  - task: Bash@3
    displayName: "K8s deployment"
    inputs:
      targetType: inline
      script: 'kubectl apply -f spc.yaml'
      workingDirectory: 'deployment/k8s'
    