trigger:
  - main 
pool: 
  name: Default 

parameters:
  - name: mavengoal
    displayName: goalmaven
    type: string
    default: package
    values:
      - package
      - clean package
      - install
      - clean install

      
resources:
  repositories:
    - repository: templates #todo it is id which is givenby us
      name: ajaykumar # todo it is repository name 
      ref: 'refs/heads/main' #todo it is branch name
      type: git
stages:
  - template: templates/build-using-maven.yaml@templates # respository id at end
    parameters:
      mavengoal: 'package'
      mavenpomfile: 'pom.xml'
      javadirectory: /usr/lib/jvm/java-17-openjdk-amd64
      content: target/spring-petclinic-3.2.0-SNAPSHOT.jar
