---

apiVersion: v1 
kind: Pod
metadata:
  name: pod-affinity
  labels:
    name: affinity 
spec:
  affinity: 
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: alpine
          topologyKey: kubernetes.io/hostname
  restartPolicy: Never
  containers:
    - name: nginx-re
      image: nginx
      ports:
        - containerPort: 80
          name: nginx        

---

---

apiVersion: v1 
kind: Pod
metadata:
  name: pod-antiaffinity
  labels:
    name: antiaffinity 
spec:
  affinity: 
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: alpine
          topologyKey: kubernetes.io/hostname
  restartPolicy: Never
  containers:
    - name: nginx-re
      image: nginx
      ports:
        - containerPort: 80
          name: nginx 


---

---
apiVersion: v1
kind: Pod
metadata:
  name: alpine
  labels:
    app: alpine
    env: dev
spec:
  containers:
    - name: alpine
      image: alpine
      args:
        - sleep
        - 1d 