version: '3.9'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: opencti_user
      POSTGRES_PASSWORD: Ajay@008
      POSTGRES_DB: opencti
    ports:
      - "5432:5432"

  elasticsearch:
    image: elasticsearch:8.6.0  # Specify a valid version here
    environment:
      discovery.type: single-node
    ports:
      - "9200:9200"
