apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-cluster1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://gitlab.com/ajay3961047/ajaymaddela.git'  # GitLab repository URL
    targetRevision: main
    path: deployment/k8s/
    # Authentication using the secret values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true