--- 

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-de
  labels: 
    app: nginx 
    env: dev
    ver: "1.0"
spec: 
  minReadySeconds: 5
  progressDeadlineSeconds: 30
  replicas: 4
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: nginx
      env: dev
      ver: "1.0"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: nginx-de
      labels:
        app: nginx
        env: dev
        ver: "1.0"
    spec:
      automountServiceAccountToken: false
      containers:
        - name: nginx-con
          image: nginx
          ports:
            - name: nginx-po
              containerPort: 80
              protocol: "TCP"
          livenessProbe:
            httpGet:
              port: 80
              path: /
          readinessProbe:
            httpGet:
              port: 80
              path: /
          restartPolicy: "Always"
          resources:
            requests:
              cpu: "50m"
              memory: "50Mi"
            limits:
              cpu: "100m"
              memory: "100Mi"
          volumeMounts: 
            - name: ajay-vol
              readOnly: true
              mountPath: /mnt
      volumes:
        - name: ajay-vol
          emptyDir:
            sizeLimit: 500Mi




---
apiVersion: v1 
kind: Service
metadata:
  name: ajay-svc
  labels:
    app: nginx 
    env: dev
    ver: "1.0"
spec:
  type: NodePort 
  selector: 
    app: nginx
    env: dev
    ver: "1.0"
  ports:  
    - name: ajay-po
      nodePort: 31000
      protocol: "TCP"
      targetPort: 80





            

            


    

      




