version: '3'
services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    volumes:
      - rabbitmqdata: /var/lib/rabbitmq
      - "./rabbitmq:/etc/pitstop/"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_CONFIG_FILE: /etc/pitstop/rabbitmq.conf

  sqlserver:
    image: mysql:8.3.0
    container_name: sqlserver
    volumes:
      - sqlserverdata:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - ACCEPT_EULA: Y
      - MYSQL_ROOT_PASSWORD: admin123
      - MYSQL_DATABASE: devops
      - MYSQL_USER: ajay 
      - MYSQL_PASSWORD: admin123

  mailserver:
    image: mailserver/docker-mailserver:13.2.0
    container_name: mailserver
    ports:
      - "25:25"
      - "993:993"
      - "143:143"
      - "587:587"
      - "4000:80"
  logserver:
    image: datalust/seq:latest
    container_name: logserver
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA: Y

  vehiclemanagementapi:
    image: pitstop/vehiclemanagementapi:1.0
    build: VehicleManagementAPI
    depends_on:
      - rabbitmq
      - sqlserver
    ports:
      - "5000"
    environment:
      - ASPNETCORE_ENVIRONMENT: Production

  customermanagementapi:
    image: pitstop/customermanagementapi:1.0
    build: CustomerManagementAPI
    depends_on:
      - rabbitmq
      - sqlserver
    ports:
      - "5100"
    environment:
      - ASPNETCORE_ENVIRONMENT: Production

  workshopmanagementapi:
    image: pitstop/workshopmanagementapi:1.0
    build: WorkshopManagementAPI
    depends_on:
      - rabbitmq
      - sqlserver
    ports:
      - "5200"
    environment:
      - ASPNETCORE_ENVIRONMENT: Production

  auditlogservice:
    image: pitstop/auditlogservice:1.0
    build: AuditlogService
    container_name: auditlogservice
    depends_on:
      - rabbitmq
    environment:
      - DOTNET_ENVIRONMENT: Production

  invoiceservice:
    image: pitstop/invoiceservice:1.0
    build: InvoiceService
    container_name: invoiceservice
    depends_on:
      - rabbitmq
      - sqlserver
      - mailserver
    environment:
      - DOTNET_ENVIRONMENT: Production

  notificationservice:
    image: pitstop/notificationservice:1.0
    build: NotificationService
    container_name: notificationservice
    depends_on:
      - rabbitmq
      - sqlserver
      - mailserver
    environment:
      - DOTNET_ENVIRONMENT: Production

  timeservice:
    image: pitstop/timeservice:1.0
    build: TimeService
    container_name: timeservice
    depends_on:
      - rabbitmq
    environment:
      - DOTNET_ENVIRONMENT: Production

  workshopmanagementeventhandler:
    image: pitstop/workshopmanagementeventhandler:1.0
    build: WorkshopManagementEventHandler
    container_name: workshopmanagementeventhandler
    depends_on:
      - rabbitmq
      - sqlserver
    environment:
      - DOTNET_ENVIRONMENT: Production

  webapp:
    image: pitstop/webapp:1.0
    build: WebApp
    container_name: webapp
    depends_on:
      - customermanagementapi
      - vehiclemanagementapi
      - workshopmanagementapi
    ports:
      - "7005:7005"
    environment:
      - ASPNETCORE_ENVIRONMENT: Production

volumes:
  sqlserverdata:
    external: true
  rabbitmqdata:
    external: true