---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  labels: 
    env: prod 
spec:
  minReadySeconds: 5
  replicas: 1
  updateStrategy:
    type: RollingUpdate 
    rollingUpdate: 
      maxUnavailable: 10%
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      env: prod 
  serviceName: rabbitmq
  template: 
    metadata:
      name: rabbitmq
      labels:
        env: prod 
    spec:
      restartPolicy: Always
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management-alpine
          ports:
            - name: rabbitmq
              containerPort: 5672
          volumeMounts:
            - mountPath: /var/lib/rabbitmq
              name: rabbitmq
            - name: rabbitmq-config
              mountPath: /etc/pitstop
          env: 
            - name: RABBITMQ_CONFIG_FILE
              value: /etc/pitstop/rabbitmq.conf
      volumes:
        - name: rabbitmq
          emptyDir: 
            medium: ""
            sizeLimit: 500Mi
        - name: rabbitmq-config
          hostPath:
            path: /etc/pitstop/rabbitmq.conf



---
apiVersion: v1 
kind: Service
metadata:
  name: rabbitmq
spec: 
  type: NodePort
  selector:
    env: prod 
  ports: 
    - name: rabbitmq
      port: 5672
      targetPort: 5672
      nodePort: 30001



---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sqlserver
  labels: 
    env: prod 
spec:
  minReadySeconds: 5
  replicas: 1
  updateStrategy:
    type: RollingUpdate 
    rollingUpdate: 
      maxUnavailable: 10%
  revisionHistoryLimit: 5
  serviceName: sqlserver
  selector:
    matchLabels: 
      env: prod 
  template: 
    metadata:
      name: sqlserver
      labels:
        env: prod 
    spec:
      restartPolicy: Always
      containers:
        - name: sqlserver
          image: mcr.microsoft.com/azure-sql-edge
          ports:
            - name: sqlserver
              containerPort: 1434
            - containerPort: 1433
          volumeMounts:
            - mountPath: /var/opt/mssql
              name: sqlserverdata 
          env: 
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_PID
              value: Developer
            - name: SA_PASSWORD
              value: 8jkGh47hnDw89Haq8LN2
             
            
              
      volumes:
        - name: sqlserverdata
          emptyDir: 
            sizeLimit: 2Gi


---
apiVersion: v1 
kind: Service
metadata:
  name: sqlserver
spec: 
  type: NodePort
  selector:
    env: prod 
  ports: 
    - name: sqlserver
      port: 1434
      targetPort: 1433
      nodePort: 30003
  