---
- name: install mysql server
  hosts: webserver
  become: yes
  tasks:
    - name: fail for unsupported os
      ansible.builtin.fail:
        msg: this is designed for Ubuntu
      when: ansible_facts['distribution'] != 'Ubuntu'
    - name: installing mysql
      ansible.builtin.apt:
        name: "{{ package }}"
        update_cache: yes
        state: present 
    - name: Create new databases with names nopdb 
      community.mysql.mysql_db:
        name: nopdb 
        state: present
      become: yes
    - name: Create database user with password and all database privileges and 'WITH GRANT OPTION'
      community.mysql.mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ password_name }}"
        host: '%'
        priv: 'nopdb.*:ALL,GRANT'
        state: present
        check_implicit_admin: true
      become: yes
   

      