---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ecr-oci-test
  namespace: argocd
spec:
  refreshInterval: 30m
  target:
    name: ecr-oci-test
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        name: ecr-oci-test
        type: helm
        enableOCI: "true"
        url: <account-number>.dkr.ecr.<aws_region>.amazonaws.com/helm/gitlab
        password: "{{ .password }}"
        username: "{{ .username }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ECRAuthorizationToken
          name: ecr