---
- name: install docker using gpg key 
  hosts: appserver
  become: yes
  tasks: 
    - name: fail for unsupported os family 
      ansible.builtin.fail: 
        msg: this works only on Ubuntu os
      when: ansible_facts['distribution'] != 'Ubuntu'
    - name: install packages
      ansible.builtin.apt:
        name: "{{ package_name }}"
        update_cache: yes
        state: present 
    - name: create directory
      ansible.builtin.file:
        path: "{{ path }}"
        state: directory
        mode: '0755'
    - name: download gpg file 
      ansible.builtin.get_url:
        url: "{{ url }}"
        dest: "{{ dest }}"
    - name: Set permissions for Docker GPG key
      ansible.builtin.file:
        path: /etc/apt/keyrings/docker.asc
        mode: '0644'
    - name: adding repository to apt sources
      ansible.builtin.command:
        cmd: "{{ command }}"
    - name: update cache 
      ansible.builtin.apt:
        update_cache: yes 
    - name: install docker packages 
      ansible.builtin.apt:
        name: "{{ docker_package }}"
        state: present 
        
        