apiVersion: v1
kind: Pod
metadata:
  name: sa1-test-pod
  namespace: default
spec:
  serviceAccountName: service-account-1
  containers:
  - name: aws-cli
    image: amazon/aws-cli
    command: ["sleep", "3600"]


# kubectl apply -f sa1-test-pod.yaml
# aws sts get-caller-identity
# aws s3 ls
