---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: nginx-cj
  labels:
    app: nginx-re 
spec: 
  jobTemplate:
    metadata:
      name: nginx-re
      labels:
        app: nginx-re
    spec: 
      backoffLimit: 3
      template: 
        metadata: 
          name: nginx-re
          labels:
            app: nginx-re
        spec:
          containers:
            - name: nginx
              image: nginx
              ports:
                - name: nginx
                  containerPort: 80
  schedule: 0 17 * * 2