---

apiVersion: v1 
kind: Pod
metadata:
  name: tomcat-re
  labels: 
    name: tomcat
    app: tomcat 
spec: 
  restartPolicy: Always
  containers: 
    - name: tomcat 
      image: tomcat:jre11
      livenessProbe: 
        grpc:
          port: 80
      ports:
        - name: tomcat-re
          containerPort: 80
      readinessProbe:
        grpc:
          port: 80 

---

apiVersion: v1
kind: Service
metadata:
  name: ajay-svc
  labels: 
    app: tomcat
spec: 
  type: NodePort
  selector:
    app: tomcat
  ports: 
    - name: tomcat-re
      nodePort: 31000
      port: 80
      targetPort: 80
  