---

apiVersion: v1 
kind: Pod 
metadata:
  name: mysql-e
spec: 
  containers:
    - name: mysql
      image: mysql:8.0-debian
      ports:
        - name: mysql-re
          containerport: 80
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: admin123
        - name: MYSQL_DATABASE
          value: emp
        - name: MYSQL_USER
          value: devops
        - name: MYSQL_PASSWORD
          value: devops@123
      resources:
        limits:
          cpu: 50m
          memory: 50Mi