---
apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: emp
  labels:
    app: httpd
spec: 
  accessModes:
    - ReadWriteOnce
  storageClassName:  managed-csi
  selector: 
    matchlabels:
      app: httpd
  resources:
    requests:
      storage: 4Gi
      

---
apiVersion: v1 
kind: Pod
metadata: 
  name: apache
  labels: 
    app: httpd
spec:
  volumes:
    - name: emp-vol
      persistentVolumeClaim:
        claimName: emp
        readOnly:  false
  restartPolicy: OnFailure
  containers: 
    - name: httpd
      image: httpd
      ports:
        - name: httpd
          containerPort: 80
      volumeMounts:
        - name: emp-vol
          mountPath: /var/lib/mysql