---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nginx
  namespace: dev
spec:
  minReadySeconds: 5
  replicas: 2
  selector: 
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
  template: 
    metadata: 
      name: nginx
      labels: 
        app: nginx
      namespace: dev
    spec:
      containers: 
        - name: nginx
          image: nginx
          ports:
            - name: nginx-re
              containerPort: 80
