---
- name: install apache2
  hosts: localhost
  become: yes
  tasks: 
    - name: install apache on ubuntu
      ansible.builtin.apt:
        name: "{{package}}"
        update_cache: yes
        state: present
      notify: 
        - enable and start apache2
    - name: install php packages
      ansible.builtin.apt:
        name: "{{ php_packages }}"
        state: present 
    - name: copy info.php
      ansible.builtin.copy:
        src: info.php
        dest: /var/www/html/info.php
  handlers:
    - name: enable and start apache2
      ansible.builtin.systemd_service:
        name: apache2
        enabled: yes
        state: started 
    - name: restart apache2
      ansible.builtin.systemd_service:
        name: apache2
        enabled: yes
        state: restarted 
      
