---
- name: install apache2
  hosts: webserver
  become: yes
  tasks: 
    - name: fail for unsupported os
      ansible.builtin.fail:
        msg: "This playbook is designed only for Ubuntu os"
      when: ansible_facts['os_distribution'] != 'Ubuntu'
    - name: install apache2 on ubuntu
      ansible.builtin.apt:
        name: "{{package}}"
        update_cache: yes
        state: present
      notify: 
        - enable and start apache2
    - name: install php packages
      ansible.builtin.apt:
        name: "{{ php_packages }}"
        state: present 
      notify:
        - restart apache2
    - name: copy info.php
      ansible.builtin.copy:
        src: info.php
        dest: /var/www/html/info.php
  handlers:
    - name: enable and start apache2
      service:
        name: apache2
        enabled: yes
        state: started 
    - name: restart apache2
      service:
        name: apache2
        state: restarted 
      
