resource_group_name  = "akki"
region               = "eastus"
virtual_network_name = "anji"
subnet_name          = "app"
network_cidr         = "10.0.0.0/16"
subnet_cidr          = "10.0.0.0/24"
network_interface    = "ltqt"
machinename          = "srinivas"